"""
Style Conciliador — second reconciliation step.
Merges the scene description with the artistic style descriptor into the
final image generation prompt. Output is saved to outputs/prompts/{id}.json.
Called by batch_runner.py.
"""

import logging
import requests
from config import OLLAMA_HOST, OLLAMA_MODEL, OLLAMA_TIMEOUT

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an expert at writing prompts for AI image generation models like Stable Diffusion and FLUX.
You will receive a scene description and an artistic style descriptor.
Your task is to produce a final image generation prompt that combines both.
Rules:
- CRITICAL: Begin the prompt with the style descriptor tags, comma-separated, BEFORE any scene or character content. This ensures the model prioritizes the art style above everything else.
- After the style tags, describe the dominant body color as a standalone descriptor BEFORE naming the Pokémon. Example: "...Ken Sugimori style, soft watercolor, clean outlines, pale beige reptile, a Normal-type Charmander..."
- This color-first structure after the style tags overrides the character's iconic coloring in the image model
- Naturally weave in the environment and atmosphere
- Write a single dense prompt, no longer than 5 sentences total
- Use descriptive, evocative language optimized for image generation
- Output only the final prompt, nothing else"""


def reconcile_style(scene_desc: str, style_desc: str) -> str:
    """Merge a scene description with a style descriptor into the final prompt.

    Args:
        scene_desc: Merged scene description from scene_conciliador.
        style_desc: Style descriptor string generated by style_agent.

    Returns:
        The final image generation prompt string.

    Raises:
        RuntimeError: If the Ollama API call fails.
    """
    # ----
    # Step 1 – Build the user prompt
    # ----
    user_prompt = (
        f"Scene description:\n{scene_desc}\n\n"
        f"Artistic style:\n{style_desc}\n\n"
        f"Write the final image generation prompt."
    )

    # ----
    # Step 2 – Call Ollama API
    # ----
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_prompt},
        ],
        "stream": False,
        "options": {"think": False},
    }

    try:
        response = requests.post(
            f"{OLLAMA_HOST}/api/chat",
            json=payload,
            timeout=OLLAMA_TIMEOUT,
        )
        response.raise_for_status()
    except requests.RequestException as e:
        logger.error("style_conciliador failed: %s", e)
        raise RuntimeError(f"Ollama request failed: {e}") from e

    # ----
    # Step 3 – Extract and return the final prompt
    # ----
    return response.json()["message"]["content"].strip()
